import { Dish } from './dish'

export const DISHES: Dish[] = [
    {
        id: 1,
        name: "rosół",
        cuisine: "polska",
        type: "zupa",
        time: "obiad",
        ingredients: "bulion drobiowy,marchewka,makaron",
        amount: 10,
        ordered: 0,
        price: 10,
        description: "Tradycyjna zupa polska",
        pictures: "rosol.jpg",
        link: "Zdjęcie",
        rating: 0
    },
    {
        id: 2,
        name: "tamagoyaki",
        cuisine: "japońska",
        type: "wegetariańskie",
        time: "śniadanie",
        ingredients: "jajka,sos sojowy",
        amount: 8,
        ordered: 0,
        price: 16,
        description: "Smażony omlet japoński w formie rolady", 
        pictures: "tamagoyaki.jpg,",
        link: "Zdjęcie",
        rating: 0
    },
    {
        id: 3,
        name: "burrito",
        cuisine: "meksykańska",
        type: "mięsne",
        time: "obiad",
        ingredients: "ryż,mięso wołowe,fasola,kukurydza",
        amount: 5,
        ordered: 0,
        price: 20,
        description: "Najlepsze burrito w mieście",
        pictures: "burrito.jpg",
        link: "Zdjęcie",
        rating: 0
    },
    {
        id: 4,
        name: "miso ramen",
        cuisine: "japońska",
        type: "zupa",
        time: "obiad",
        ingredients: "bulion warzywny,pasta miso,makaron,jajka,mięso wieprzowe,nori",
        amount: 8,
        ordered: 0,
        price:25,
        description: "Tradycyjna zupa japońska",
        pictures: "ramen.jpg",
        link: "Zdjęcie",
        rating: 0
    },
    {
        id:5,
        name: "mochi",
        cuisine: "japońska",
        type: "ciastka",
        time: "deser",
        ingredients: "ryż, nadzienie truskawkowe,liście yomogi",
        amount: 30,
        ordered: 0,
        price: 8,
        description: "tradycyjne japońskie kluski/ciastka robione z klejącego ryżu",
        pictures: "mochi.jpg",
        link: "Zdjęcie",
        rating: 0
    },
    {
        id: 6,
        name: "sałatka grecka",
        cuisine: "grecka",
        type: "sałatka",
        time: "przystawka",
        ingredients: "ogórek,pomidor,cebula czerwona,oliwki,ser feta",
        amount: 12,
        ordered: 0,
        price: 18,
        description: "Klasyczna sałatka ze świeżo krojonych warzyw",
        pictures: "grecka.jpg",
        link: "Zdjęcie",
        rating: 0
    },
    {
        id: 7,
        name: "spaghetti bolognese",
        cuisine: "włoska",
        type: "makaron",
        time: "obiad",
        ingredients: "mięso mielone,sos pomidorowy,makaron",
        amount: 16,
        ordered: 0,
        price: 23,
        description: "Klasyczne danie kuchni włoskiej",
        pictures: "bolognese.jpg",
        link: "Zdjęcie",
        rating: 0
    },
    {
        id: 8,
        name: "pancake's",
        cuisine: "amerykańska",
        type: "ciasto",
        time: "deser",
        ingredients: "placki,truskawki,borówki,masło,syrop klonowy",
        amount: 8,
        ordered: 0,
        price: 20,
        description: "Przepyszny deser amerykański",
        pictures: "pancake.jpg",
        link: "Zdjęcie",
        rating: 0
    },
    {
        id: 9,
        name: "naleśniki",
        cuisine: "francuska",
        type: "ciasto",
        time: "deser",
        ingredients: "bita śmietana,sos czekoladowy,twaróg",
        amount: 10,
        ordered: 0,
        price: 11,
        description: "Cienke placki z twarogiem, polane sosem czekoladowym i bita śmietaną",
        pictures: "nalesniki.jpg",
        link: "Zdjęcie",
        rating: 0
    },
    {
        id: 10,
        name: "lasagna",
        cuisine: "włoska",
        type: "mięsne",
        time: "obiad",
        ingredients: "makaron lasagna,mięso mielone,ser,sos beszamelowy",
        amount: 17,
        ordered: 0,
        price: 19,
        description: "Jedno z najbardziej znanych dań kuchni włoskiej",
        pictures: "lasagna.jpg",
        link: "Zdjęcie",
        rating: 0
    },
    {
        id: 11,
        name: "focaccia",
        cuisine: "włoska",
        type: "chleb",
        time: "przystawka",
        ingredients: "ciasto drożdzowe,oliwa,oliwki,cebula",
        amount: 18,
        ordered: 0,
        price: 10,
        description: "Włoskie pieczywo, polane oliwą, podane z oliwkami",
        pictures: "focaccia.jpg",
        link: "Zdjęcie",
        rating: 0
    },
    
    {
        id: 12,
        name: "shakshuka",
        cuisine: "bliskowschodnia",
        type: "wegetariańskie",
        time: "śniadanie",
        ingredients: "pomidory,papryka,cebula,jajka",
        amount: 13,
        ordered: 0,
        price: 18,
        description: "Jednogarnkowe danie kuchni tunezyjskiej",
        pictures: "shakshuka.jpg,",
        link: "Zdjęcie",
        rating: 0
    },
]